//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCalculator.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCalculator.Common.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Net calculator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available IP addresses in major network.
        /// </summary>
        public static string AvailableAddressesMajorNetwork {
            get {
                return ResourceManager.GetString("AvailableAddressesMajorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available IP addresses in allocated subnets.
        /// </summary>
        public static string AvailableAddressesSubnets {
            get {
                return ResourceManager.GetString("AvailableAddressesSubnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broadcast direction.
        /// </summary>
        public static string BroadcastAddress {
            get {
                return ResourceManager.GetString("BroadcastAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Byte #{0} is out of allowed range {1}.
        /// </summary>
        public static string ByteOutOfRangeError {
            get {
                return ResourceManager.GetString("ByteOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default gateway.
        /// </summary>
        public static string DefaultGateway {
            get {
                return ResourceManager.GetString("DefaultGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed operation.
        /// </summary>
        public static string FailedOperation {
            get {
                return ResourceManager.GetString("FailedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First host.
        /// </summary>
        public static string FirstHost {
            get {
                return ResourceManager.GetString("FirstHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fixed mask.
        /// </summary>
        public static string FixedMask {
            get {
                return ResourceManager.GetString("FixedMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host range.
        /// </summary>
        public static string HostRange {
            get {
                return ResourceManager.GetString("HostRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hosts.
        /// </summary>
        public static string Hosts {
            get {
                return ResourceManager.GetString("Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last host.
        /// </summary>
        public static string LastHost {
            get {
                return ResourceManager.GetString("LastHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Major network.
        /// </summary>
        public static string MajorNetwork {
            get {
                return ResourceManager.GetString("MajorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Major network IP.
        /// </summary>
        public static string MajorNetworkIp {
            get {
                return ResourceManager.GetString("MajorNetworkIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Major network mask.
        /// </summary>
        public static string MajorNetworkMask {
            get {
                return ResourceManager.GetString("MajorNetworkMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mask.
        /// </summary>
        public static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Byte #{0} has an incorrect binary value ({1}).
        /// </summary>
        public static string MaskByteInvalidValueError {
            get {
                return ResourceManager.GetString("MaskByteInvalidValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mask is out of allowed range {0}.
        /// </summary>
        public static string MaskCIDROutOfRange {
            get {
                return ResourceManager.GetString("MaskCIDROutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Net.
        /// </summary>
        public static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Net address.
        /// </summary>
        public static string NetAddress {
            get {
                return ResourceManager.GetString("NetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Net IP.
        /// </summary>
        public static string NetIp {
            get {
                return ResourceManager.GetString("NetIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of IP addresses needed.
        /// </summary>
        public static string NumberAddressesNeeded {
            get {
                return ResourceManager.GetString("NumberAddressesNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of subnets.
        /// </summary>
        public static string NumberSubnets {
            get {
                return ResourceManager.GetString("NumberSubnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subnets.
        /// </summary>
        public static string Subnets {
            get {
                return ResourceManager.GetString("Subnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful operation.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use CIDR.
        /// </summary>
        public static string UseCIDR {
            get {
                return ResourceManager.GetString("UseCIDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variable mask.
        /// </summary>
        public static string VariableMask {
            get {
                return ResourceManager.GetString("VariableMask", resourceCulture);
            }
        }
    }
}
